### PR TITLE
fix: getRequestUrl for cases with a list of sort objects

### PR DESCRIPTION
**Pull request by kitcat-dev**
Hello.

As mentioned in the https://github.com/grikomsn/airtable-deno/issues/7, I made some changes to the function `getRequestUrl` in `airtable.ts`. I also moved the sort type to the `SortSelectOption` interface and wrote a couple of tests.

Please write your opinion. I can change anything that doesn't fit with your vision of the library :)

### CODE REVIEW

**Comment by grikomsn** [comment]
Neat! Remind me to check on it this weekend. Need to upgrade my Deno runtime on my workstation and test this. 😄

**Comment by albertmolodec** [comment]
No problem. I can remind you in a couple of days.

**Comment by albertmolodec** [comment]
@grikomsn Hello 👋
Could you take a look at this PR? :-)

**Comment by lino-levan** [comment]
@grikomsn Any update?

**Comment by isaced** [comment]
@grikomsn Hello buddy, it works, can you merge this PR?

**Pull request closed without merging**
